
[project]
name = "tqsim"
version = "1.0.0"
description = "TQSim is a Topological Quantum Computing simulator based on Anyon models"
authors = [
    { name = "CQTech.org", email = "constantinequantumtech@gmail.com" },
    { name = "Abdellah Tounsi", email = "abdellah.touni@umc.edu.dz" },
    { name = "Mohamed Messaoud Louamri", email = "mm.louamri@gmail.com" },
    { name = "Nacer eddine Belaloui", email = "n.aityahia.belaloui@gmail.com" },
    { name = "Mohamed Taha Rouabah", email = "m.t.rouabah@gmail.com" },
]
requires-python = ">=3.11"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
keywords = ["topological quantum computing", "quantum", "quantum computing", "anyons", "simulator"]
urls = { repository = "https://github.com/Constantine-Quantum-Tech/tqsim" }
dependencies = [
    "matplotlib>=3.10",
    "numpy>=2.3.0",
    "seaborn>=0.13",
]

[dependency-groups]
dev = [
    "pytest>=8.3.0",
]

[tool.isort]
profile = "black"